### ISSUE TITLE
TRACKING: Rewrite Fission CLI

### ISSUE THREAD

**Issue by bgins** [fission-codes/fission-cli#1]
We're rewriting the Fission CLI in Rust.

### Tasks

- [x] [Add generate credentials command](https://github.com/fission-codes/fission-cli/issues/2)
- [ ] [Add IPFS trait and communication layer](https://github.com/fission-codes/fission-cli/issues/7)
- [x] [Wrap existing CLI](https://github.com/fission-codes/fission-cli/issues/6)
- [ ] [Add setup command](https://github.com/fission-codes/fission-cli/issues/9)
- [ ] Add user commands
  - [ ] [Add user login command](https://github.com/fission-codes/fission-cli/issues/22)
  - [ ] [Add user whoami command](https://github.com/fission-codes/fission-cli/issues/23)
- [ ] Add app commands
  - [ ] [Add app register command](https://github.com/fission-codes/fission-cli/issues/24)
  - [ ] [Add app publish command](https://github.com/fission-codes/fission-cli/issues/25)
  - [ ] [Add app list command](https://github.com/fission-codes/fission-cli/issues/26) (new command)
  - [ ] [Add app destroy command](https://github.com/fission-codes/fission-cli/issues/27) (new command)
  - [ ] [Add app delegate command](https://github.com/fission-codes/fission-cli/issues/28)
- [ ] [Add tracing or a logging library for verbose an quiet mode](https://github.com/fission-codes/fission-cli/issues/31)
- [ ] [Add remote flag](https://github.com/fission-codes/fission-cli/issues/33)
- [ ] [Add version flag](https://github.com/fission-codes/fission-cli/issues/34)
- [x] [Add Contributing Guide](https://github.com/fission-codes/fission-cli/issues/16)
- [x] [Add Read Me](https://github.com/fission-codes/fission-cli/issues/15)
- [x] [Add License](https://github.com/fission-codes/fission-cli/issues/12)
- [ ] [Add Github Actions](https://github.com/fission-codes/fission-cli/issues/38)
- [x] [Add Community Guidelines](https://github.com/fission-codes/fission-cli/issues/40)
- [x] Add help flag and implementation
  - Implemented in https://github.com/fission-codes/fission-cli/issues/6

Note that we will want to make sure the rewritten CLI is compatible with the existing CLI config files. If it is not, we should migrate to provide backwards compatibility.

### The Problem
Currently the Fission Cli is written in rust. This is not ideal as Haskell has a number of issues including bad package management, bad support for compiling for windows, no support for compiling to Web Assembly, and more. In order to get around these issues we are rewriting the Fission Cli and other Fission apps like WINFS in Rust.
